name: test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      # 서비스 연결 코드
      # - name: Check PowerShell
      #   run: $PSVersionTable

      # 소스코드 내려받는 코드
      - name: Checkout repository
        uses: actions/checkout@v4
        # with:
        #   path: .

      # node 버전 확인
      # - name: Check Node.js version
      #   run: node -v
      
      # node 모듈 다운로드 (`package.json`이 존재하는 경로가 필요함)
      - name: npm install
        working-directory: ./frontend
        run: npm i