name: test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      runs-on: self-hosted
      steps:
        - name: Check PowerShell
          run: $PSVersionTable